
# Operasi Matematika & Numpy
Sebelum lanjut, harap:
1. Jika menggunakan jupyter, silahkan pilih "File" --> "Download" --> "Download .ipynb"
2. Jika menggunakan colab, silahkan pilih "File" --> "Save a copy in drive"

In [ ]:
import numpy as np

### Pengenalan array

In [ ]:
#1D array
a = np.array([1, 3, 0])
print('banyaknya entry = ', a.size)
print('dimensi array = ', a.ndim)
print('ukuran array = ', a.shape)

banyaknya entry =  3
dimensi array =  1
ukuran array =  (3,)


In [ ]:
#Slicing
a[:]

array([1, 3, 0])

In [ ]:
#Slicing
a[:2]

array([1, 3])

In [ ]:
#Slicing
a[2]

0

In [ ]:
#Slicing
a[1:]

array([3, 0])

In [ ]:
print('a[1:3] = ', a[1:3])
print('a[:3] = ', a[:3])

a[1:3] =  [3 0]
a[:3] =  [1 3 0]


In [ ]:
#2D Array (Matriks)
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# 1D to 2D matrix
x = np.array([1,2,3,4,5,6,7,8,9])
x2 = np.reshape(x,(3,3))
print('Matrix 1D :\n', x)
print('Matrix 2D :\n', x2)

Matrix 1D :
 [1 2 3 4 5 6 7 8 9]
Matrix 2D :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


###Latihan-2 (2D array)

In [ ]:
#Lengkapi kodingan berikut
print('banyaknya entry = ', A.size )
print('dimensi array = ', A.ndim )
print('ukuran array = ', A.shape )

banyaknya entry =  9
dimensi array =  2
ukuran array =  (3, 3)


In [ ]:
#Slicing
print('baris ke-2 = ', A[1])
print('entry ke-2 & 3 baris ke-2 = ', A[1, 1:])
print('entry pertama & 2 kolom ke-2 = ', A[:2, 1])

baris ke-2 =  [4 5 6]
entry ke-2 & 3 baris ke-2 =  [5 6]
entry pertama & 2 kolom ke-2 =  [2 5]


###Latihan-3 (Slicing)

In [ ]:
#Lengkapi kodingan berikut
print('baris ke-3 = ', A[2])
print('entry ke-1 & 2 baris ke-3 = ', A[2,0:2])
print('entry ke-2 & 3 kolom ke-3 = ', A[1:,2])

baris ke-3 =  [7 8 9]
entry ke-1 & 2 baris ke-3 =  [7 8]
entry ke-2 & 3 kolom ke-3 =  [6 9]


output jawaban:
baris ke-3 =  [7 8 9]

entry ke-1 & 2 baris ke-3 =  [7 8]

entry ke-2 & 3 kolom ke-3 =  [6 9]

### Operasi Matematika di Numpy

In [ ]:
C = A*A
print('perkalian antar entry = ')
print(C)

perkalian antar entry = 
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [ ]:
print('perkalian matriks = ')
print(np.matmul(A,A))
print()
print(np.dot(A,A))

perkalian matriks = 
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


Bisa dilihat perbedaan perkalian antar entry dan perkalian matriks biasa?

In [ ]:
print('determinan matriks A = ', np.linalg.det(A))
print('determinan matriks C = ', np.linalg.det(C))

determinan matriks A =  0.0
determinan matriks C =  -216.00000000000006


In [ ]:
print('nilai dan vektor eigen matriks A = ', 
      np.linalg.eig(A))

nilai dan vektor eigen matriks A =  (array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))


In [ ]:
print('nilai eigen matriks A = ', np.linalg.eig(A)[0])

nilai eigen matriks A =  [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]


In [ ]:
print('vektor eigen matriks A = ')
print(np.linalg.eig(A)[1])

vektor eigen matriks A = 
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [ ]:
e_vec = np.linalg.eig(A)[1][:,0] #Menagambil eigen vector pertama ([-0.23197, -0.52532209, -0.8186735  ])
e_val = np.linalg.eig(A)[0][0] #Mengambil eigen value pertama (1.61168440e+01)
print(e_vec)
print(e_val)

[-0.23197069 -0.52532209 -0.8186735 ]
16.116843969807043


In [ ]:
print(np.matmul(A, e_vec)) #hasil A * eigen vector

[ -3.73863537  -8.46653421 -13.19443305]


In [ ]:
print(e_val*e_vec) #hasil eigen value * eigen vector (Hasilnya sama)

[ -3.73863537  -8.46653421 -13.19443305]


### Latihan-4 (Operasi matriks)

In [ ]:
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])

Hitunglah:
*   2*A
*   2+A
*   A+B
*   A-B
*   determinan A
*   invers dari B, simpan jadi matriks D
*   transpose D
*   nilai eigen dan vektor eigen dari A dan B







In [ ]:
#Ketik Kode disini
print('Hasil dari 2*A :')
print(2*A)
print()
print('Hasil dari 2+A :')
print(2+A)
print()
print('Hasil dari A+B :')
print(A+B)
print()
print('Hasil dari A-B :')
print(A-B)
print()
print('Nilai dari det(A) :')
print(np.linalg.det(A))
print()

D = np.linalg.inv(B)
print('Nilai dari D :')
print(D)
print()
print('Nilai dari Transpose D :')
print(np.transpose(D))
print()
print('Eigen Value A :')
print(np.linalg.eig(A)[0])
print()
print('Eigen Value B :')
print(np.linalg.eig(B)[0])
print()
print('Eigen Vector A :')
print(np.linalg.eig(A)[1])
print()
print('Eigen Vector B :')
print(np.linalg.eig(B)[1])
print()

Hasil dari 2*A :
[[ 2  4]
 [14 16]]

Hasil dari 2+A :
[[ 3  4]
 [ 9 10]]

Hasil dari A+B :
[[ 4  7]
 [ 8 14]]

Hasil dari A-B :
[[-2 -3]
 [ 6  2]]

Nilai dari det(A) :
-6.0

Nilai dari D :
[[ 0.46153846 -0.38461538]
 [-0.07692308  0.23076923]]

Nilai dari Transpose D :
[[ 0.46153846 -0.07692308]
 [-0.38461538  0.23076923]]

Eigen Value A :
[-0.62347538  9.62347538]

Eigen Value B :
[1.8074176 7.1925824]

Eigen Vector A :
[[-0.77640358 -0.22592838]
 [ 0.63023605 -0.97414391]]

Eigen Vector B :
[[-0.97271381 -0.76626443]
 [ 0.23200828 -0.64252535]]



Apa perbedaan dari B*D (perkalian antar entry di B dan D) dan BD (perkalian matriks B dan D)? 

In [ ]:
#Tunjukkan bedanya di kodingan di bawah ini
print('Perkalian entry =')
print(B*D)
print()
print('Perkalian matriks =')
print(np.matmul(B,D))

Perkalian entry =
[[ 1.38461538 -1.92307692]
 [-0.07692308  1.38461538]]

Perkalian matriks =
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


output jawaban: 

perkalian entry = [[ 1.38461538, -1.92307692], [-0.07692308,  1.38461538]]

perkalian matriks = [[ 1.00000000e+00, -1.11022302e-16],
       [ 1.11022302e-16,  1.00000000e+00]]
